# Generated by Django 5.0.2 on 2024-02-18 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteupdatehistory',
            old_name='new_content',
            new_name='old_content',
        ),
        migrations.RemoveField(
            model_name='noteupdatehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=datetime.datetime(2024, 2, 18, 14, 40, 17, 716743, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noteupdatehistory',
            name='old_title',
            field=models.CharField(default='old_data', max_length=255),
            preserve_default=False,
        ),
    ]
